# Generated by Django 3.2.6 on 2021-08-14 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('update', models.DateTimeField(auto_now=True)),
                ('deprecate', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر سنجی',
                'verbose_name_plural': 'نظر سنجی ها',
            },
        ),
        migrations.CreateModel(
            name='Responde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان پاسخ')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.poll', verbose_name='نظر')),
            ],
            options={
                'verbose_name': 'پاسخ نظر سنجی',
                'verbose_name_plural': 'پاسخ نظر سنجی ها',
            },
        ),
    ]
