# Generated by Django 3.2.6 on 2021-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='rand_title',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='دامنه'),
        ),
    ]
